'use strict';

const WORD_PROFILES = {
  cat: { difficulty: 1, sounds: ['k', 'æ', 't'], easierWords: ['ant'], relatedWords: ['kangaroo', 'crab'] },
  dog: { difficulty: 1, sounds: ['d', 'ɒ', 'g'], easierWords: ['deer'], relatedWords: ['goose'] },
  fish: { difficulty: 2, sounds: ['f', 'ɪ', 'ʃ'], easierWords: ['fox'], relatedWords: ['chick', 'jellyfish'] },
  bird: { difficulty: 2, sounds: ['b', 'ɜː', 'd'], easierWords: ['book'], relatedWords: ['buffalo', 'butterfly'] },
  worm: { difficulty: 2, sounds: ['w', 'ɜː', 'm'], relatedWords: ['whale', 'walk'] },
  whale: { difficulty: 2, sounds: ['w', 'eɪ', 'l'], easierWords: ['worm'], relatedWords: ['walk'] },
  turtle: { difficulty: 3, sounds: ['t', 'ɜː', 't', 'əl'], easierWords: ['cat', 'ant'], relatedWords: ['tiger'] },
  tiger: { difficulty: 3, sounds: ['t', 'aɪ', 'gə'], easierWords: ['dog'], relatedWords: ['turtle'] },
  snail: { difficulty: 3, sounds: ['s', 'n', 'eɪ', 'l'], easierWords: ['goose'], relatedWords: ['desk'] },
  pigeon: { difficulty: 3, sounds: ['p', 'ɪ', 'dʒ', 'ən'], easierWords: ['hippo'], relatedWords: ['penguin'] },
  penguin: { difficulty: 4, sounds: ['p', 'e', 'ŋ', 'gwɪn'], easierWords: ['pigeon'], relatedWords: ['mango'] },
  mosquito: { difficulty: 5, sounds: ['m', 'ɒ', 'sk', 'iː', 'təʊ'], easierWords: ['worm'], relatedWords: ['desk'] },
  leopard: { difficulty: 3, sounds: ['l', 'e', 'p', 'əd'], easierWords: ['apple'], relatedWords: ['hippo'] },
  kangaroo: { difficulty: 5, sounds: ['k', 'æ', 'ŋg', 'ə', 'ruː'], easierWords: ['cat'], relatedWords: ['crab'] },
  jellyfish: { difficulty: 5, sounds: ['dʒ', 'e', 'l', 'i', 'f', 'ɪʃ'], easierWords: ['fish'], relatedWords: ['jump'] },
  horse: { difficulty: 2, sounds: ['h', 'ɔː', 's'], easierWords: ['goose'], relatedWords: ['hippo'] },
  hippo: { difficulty: 3, sounds: ['h', 'ɪ', 'p', 'əʊ'], easierWords: ['horse'], relatedWords: ['pigeon'] },
  goose: { difficulty: 2, sounds: ['g', 'uː', 's'], easierWords: ['dog'], relatedWords: ['horse'] },
  fox: { difficulty: 2, sounds: ['f', 'ɒ', 'ks'], easierWords: ['fish'], relatedWords: ['book'] },
  elephant: { difficulty: 5, sounds: ['e', 'l', 'ə', 'f', 'ənt'], easierWords: ['eagle', 'ant'], relatedWords: ['buffalo'] },
  eagle: { difficulty: 3, sounds: ['iː', 'g', 'əl'], easierWords: ['goose'], relatedWords: ['deer'] },
  deer: { difficulty: 1, sounds: ['d', 'ɪə'], easierWords: ['dog'], relatedWords: ['desk'] },
  crab: { difficulty: 3, sounds: ['k', 'r', 'æ', 'b'], easierWords: ['cat'], relatedWords: ['kangaroo'] },
  cow: { difficulty: 1, sounds: ['k', 'aʊ'], easierWords: ['cat'], relatedWords: ['crab'] },
  chick: { difficulty: 2, sounds: ['tʃ', 'ɪ', 'k'], easierWords: ['cat'], relatedWords: ['fish'] },
  butterfly: { difficulty: 5, sounds: ['b', 'ʌ', 't', 'ə', 'flaɪ'], easierWords: ['bird', 'buffalo'], relatedWords: ['buffalo'] },
  buffalo: { difficulty: 5, sounds: ['b', 'ʌ', 'f', 'ə', 'ləʊ'], easierWords: ['bird'], relatedWords: ['butterfly'] },
  ant: { difficulty: 1, sounds: ['æ', 'n', 't'], easierWords: ['cat'], relatedWords: ['elephant'] },
  book: { difficulty: 1, sounds: ['b', 'ʊ', 'k'], easierWords: ['bird'], relatedWords: ['desk'] },
  desk: { difficulty: 2, sounds: ['d', 'e', 'sk'], easierWords: ['deer'], relatedWords: ['snail'] },
  apple: { difficulty: 2, sounds: ['a', 'p', 'əl'], easierWords: ['ant'], relatedWords: ['leopard'] },
  mango: { difficulty: 3, sounds: ['m', 'æ', 'ŋgəʊ'], easierWords: ['worm'], relatedWords: ['penguin'] },
  walk: { difficulty: 2, sounds: ['w', 'ɔː', 'k'], easierWords: ['worm'], relatedWords: ['whale'] },
  jump: { difficulty: 3, sounds: ['dʒ', 'ʌ', 'mp'], easierWords: ['jellyfish'], relatedWords: ['butterfly'] },
};

module.exports = { WORD_PROFILES };
